kind: ServiceAccount
apiVersion: v1
metadata:
  name: daskkubernetes
  namespace: default

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daskkubernetes-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daskkubernetes-binding
subjects:
- kind: ServiceAccount
  name: daskkubernetes
  namespace: default
roleRef:
  kind: ClusterRole
  name: daskkubernetes-role
  apiGroup: rbac.authorization.k8s.io
