kind: ServiceAccount
apiVersion: v1
metadata:
  name: daskkubernetes
  namespace: default

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
- kind: User
  name: yugiohrajat1@gmail.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daskkubernetes-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daskkubernetes-binding
subjects:
- kind: ServiceAccount
  name: daskkubernetes
  namespace: default
roleRef:
  kind: ClusterRole
  name: daskkubernetes-role
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-grantor
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["bind"]
  resourceNames: ["admin","edit","view"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-grantor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-grantor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: yugiohrajat1@gmail.com
