apiVersion: v1
kind: Service
metadata:
  name: svc-notebooks
spec:
  type: LoadBalancer
  selector:
    app: dask-notebook
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
    name: jupyter
  - protocol: TCP
    port: 8889
    targetPort: 8889
    name: tensorboard 
  - protocol: TCP
    port: 8787
    targetPort: 8787
    name: dask-UI 
