version: '3'

services:

  scheduler:

    build:
      context: .
      dockerfile: DockerfileScheduler

    image: rajatr/devito-dask-kube-scheduler

    ports:
      - 8888:8888

  worker:
  
    build:
      context: .
      dockerfile: docker/DockerfileWorker
  
    image: rajatr/devito-dask-kube-worker
  
    ports:
      - 8888:8888
