kind: Pod
metadata:
  labels:
    role: worker
spec:
  restartPolicy: Never
  containers:
  - image: gcr.io/devito-with-tf-and-dask-dist/devito-dask-kube-worker:latest
    imagePullPolicy: Always
    args: [dask-worker, --nthreads, '1', --no-bokeh, --memory-limit, 2GB, --death-timeout, '60']
    name: fwi-shot
    resources:
      requests:
        cpu: 300m
        memory: 1500Mi
      limits:
        cpu: 500m
        memory: 2000Mi
